### ISSUE TITLE
该插件与Tool-Bench冲突，能否改进实现兼容

### ISSUE THREAD

**Issue by Einstein-schrodinger** [halo-sigs/plugin-katex#10]
halo博客无法实现自定义元素（标签）的渲染，需要依赖Tool-Bench插件，但是katex插件与Tool-Bench插件冲突，导致公式无法渲染。
https://github.com/DioxideCN/Tool-Bench/issues/4

**Comment by gengxiaoxiaoxin** [comment]
这个插件只是根据提供的元素tag，渲染相应的公示内容。需要确认是否是因为其他插件更改了html的内容

**Comment by Einstein-schrodinger** [comment]
> 这个插件只是根据提供的元素tag，渲染相应的公示内容。需要确认是否是因为其他插件更改了html的内容

Tool-Bench插件作者的回复是这样的
![image](https://github.com/halo-sigs/plugin-katex/assets/62790820/15940315-2e23-47e2-b73d-b7c858cab0ec)

**Comment by gengxiaoxiaoxin** [comment]
> halo博客无法实现自定义元素（标签）的渲染，需要依赖Tool-Bench插件，但是katex插件与Tool-Bench插件冲突，导致公式无法渲染。 [DioxideCN/Tool-Bench#4](https://github.com/DioxideCN/Tool-Bench/issues/4)

就这个问题来说，这个仓库本身应该没什么需要做的。

PS：如果让这个插件的JS代码优先执行，可能会有效果？
