### ISSUE TITLE
能否为静态资源添加Cache-Control以启用浏览器缓存

### ISSUE THREAD

**Issue by happyZYM** [halo-sigs/plugin-katex#15]
![图片](https://github.com/halo-sigs/plugin-katex/assets/33191271/88453d72-58eb-493a-b567-82d95b5649fc)
katex.js文件比较大，有时传输耗时较长，如果能启用浏览器缓存，应该可以显著优化用户体验

**Comment by xinkeng0** [comment]
等待halo处理
- https://github.com/halo-dev/halo/issues/5357
