### ISSUE TITLE
latex公式预览正常，发布后的文章没有正常显示

### ISSUE THREAD

**Issue by pandalabme** [halo-sigs/plugin-katex#16]
halo版本:2.10
katex版本:2.0.0
文章地址: https://pandalab.me/archives/different_perspective_of_line_regression
插件启用截图：
![image](https://github.com/halo-sigs/plugin-katex/assets/141545683/55567393-4808-4b14-a5e9-6ae8493bf44e)
文章编辑预览截图：
![image](https://github.com/halo-sigs/plugin-katex/assets/141545683/38ec27b4-11ba-4baf-8b59-dadb4e8b1cd6)
显示异常截图：
![image](https://github.com/halo-sigs/plugin-katex/assets/141545683/70e5aeba-cb27-4ce1-86b6-feaca0bcc11f)

**Comment by xinkeng0** [comment]
插件配置项如何配置的？

**Comment by pandalabme** [comment]
> 插件配置项如何配置的？
没改过配置，默认配置？

![image](https://github.com/halo-sigs/plugin-katex/assets/141545683/59f73975-1541-48b2-95f3-a2e45e393170)
![image](https://github.com/halo-sigs/plugin-katex/assets/141545683/08bf5604-09a8-4aac-9463-5e37bee69d24)

**Comment by xinkeng0** [comment]
https://github.com/halo-sigs/plugin-katex/blob/main/README.md#%E7%94%A8%E6%B3%95%E8%AF%B4%E6%98%8E
