### ISSUE TITLE
无法正确显示latex中上标的写法

### ISSUE THREAD

**Issue by Litbay** [halo-sigs/plugin-katex#17]
### 环境

docker halo 2.14.0；katex 2.1.0

### issue描述

在markdown编辑器中书写`$^{[1]}$`可以正常显示为上标，但发布后无法正常显示，显示为latex原文$^{[1]}$

**Comment by xinkeng0** [comment]
使用的编辑器是？

**Comment by Litbay** [comment]
> 使用的编辑器是？

在obsidian书写，使用插件上传至halo，在halo后台使用ByteMD和Vditor Markdown两个编辑器，在编辑器内均可以正常显示

**Comment by xinkeng0** [comment]
duplicate #16

**Comment by Litbay** [comment]
> duplicate #16

解决了，感谢，问题主要是由obsidian插件直接发布的文章内没有katex的CSS选择器，用halo的编辑器重新发布一次就正常显示了
