### ISSUE TITLE
bug反馈：在含有katex 公式的文章页，疑似会给整个 body 添加 20px 的 padding

### ISSUE THREAD

**Issue by holwell** [halo-sigs/plugin-katex#23]
应该不是主题问题，我好像在多个主题中都发现了这个问题，可能是 katex 插件的问题。

**Comment by xinkeng0** [comment]
文章地址发下

**Comment by holwell** [comment]
> 文章地址发下

[文章地址](http://121.37.2.158/archives/9KM6PIsc)

**Comment by holwell** [comment]
> 文章地址发下

问题定位到了，是我自己在富文本模式下添加了一个样式导致的，和插件没关系！
