### ISSUE TITLE
stackedit 编辑器下无法渲染 Katex 公式

### ISSUE THREAD

**Issue by doubleki7461** [halo-sigs/plugin-katex#5]
Katex 插件启用后无法正常渲染 Katex 公式，无论是行间公式，行内公式均无法正常显示

katex 代码：

```katex
$$n_{ka} = \sum \limits_{i = 1}^a {(i -1) \times k + 1} = \frac {(1 + k(a - 1) + 1) \times a}{2}$$

$n_{ka} = \sum \limits_{i = 1}^a {(i -1) \times k + 1} = \frac {(1 + k(a - 1) + 1) \times a}{2}$

$$
n_{ka} = \sum \limits_{i = 1}^a {(i -1) \times k + 1} = \frac {(1 + k(a - 1) + 1) \times a}{2}
$$
```
以上代码均无法正常渲染

blog 链接：https://blog.kierankihn.com/archives/test

**Comment by doubleki7461** [comment]
以及插件好像会错误渲染非 Katex 内容为 Katex 格式

为打开插件时：

![未打开插件](https://github.com/halo-sigs/plugin-katex/assets/114803508/fa597272-d29f-48d4-a409-8fdff2954b6b)

打开插件时：

![打开插件](https://github.com/halo-sigs/plugin-katex/assets/114803508/045ab4b7-c903-422d-978d-bebc593c60b0)

**Comment by gengxiaoxiaoxin** [comment]
此插件分为2个部分。
1. 对 richer-editor的公式扩展（会影响编辑器生成的HTML）
2. 文章页使用KaTex.js渲染公式。

`$$n_{ka} = \sum \limits_{i = 1}^a {(i -1) \times k + 1} = \frac {(1 + k(a - 1) + 1) \times a}{2}$$`
这个公式我这边测试Katex.js是可以渲染的，所以需要确认下stackedit编辑器生成的HTML格式。

**Comment by gengxiaoxiaoxin** [comment]
> 以及插件好像会错误渲染非 Katex 内容为 Katex 格式
> 
> 为打开插件时：
> 
> ![未打开插件](https://user-images.githubusercontent.com/114803508/252123377-fa597272-d29f-48d4-a409-8fdff2954b6b.png)
> 
> 打开插件时：
> 
> ![打开插件](https://user-images.githubusercontent.com/114803508/252123415-045ab4b7-c903-422d-978d-bebc593c60b0.png)

这个是目前KaTex渲染的规则为：
```
delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
              {left: '\(', right: '\)', display: false},
              {left: '\[', right: '\]', display: true}
 ],
```
看来需要去除这俩种：
```
delimiters: [
              {left: '\(', right: '\)', display: false},
              {left: '\[', right: '\]', display: true}
```

**Comment by doubleki7461** [comment]
我使用默认的富文本编辑器尝试了一下，发现确实可以展示上述公式

但是使用 stackedit 编辑器的 KaTeX 公式无法正常显示，发现同一个公式会部分展示为 KaTeX，另一部分会以文本形式展示

stackedit 的公式改为`[]`的格式就可以正常在文章页面展示，但在 stackedit 里无法预览

![image](https://github.com/halo-sigs/plugin-katex/assets/114803508/c971d8be-d78f-485e-bb43-fc05ea368bf3)

图中上两个公式使用的是 `$$$$`，下边使用的是 `[]`
