### ISSUE TITLE
md编辑器怎么用这个?

### ISSUE THREAD

**Issue by xiongtete0519** [halo-sigs/plugin-katex#9]
我想要渲染Latex公式，
`stackedit: .katex--inline`
这一行配置要加在哪里？插件那里写的没看懂

**Comment by ruibaby** [comment]
插件设置。

<img width="771" alt="image" src="https://github.com/halo-sigs/plugin-katex/assets/21301288/c25c04d2-d985-4761-b4bf-499c42385f66">

/kind support

**Comment by xiongtete0519** [comment]
Halo版本2.9 ，没找到设置插件这个地方
![image](https://github.com/halo-sigs/plugin-katex/assets/66518135/8e4b8f74-b7ad-4b38-8b76-e1a0773325c8)

**Comment by xiongtete0519** [comment]
感谢，问题已解决

**Comment by MaiSR9527** [comment]
![image](https://github.com/halo-sigs/plugin-katex/assets/38725713/b5f1944d-c26b-408a-b135-3ed73a5a6e52)
配置没有效果，实在没搞懂

**Comment by MaiSR9527** [comment]
ByteMD并不支持，换成stackedit才能渲染

**Comment by ruibaby** [comment]
1.2.0 就已经支持数学公式的渲染了，你用的版本是？

https://github.com/halo-sigs/plugin-bytemd/releases/tag/v1.2.0

**Comment by MaiSR9527** [comment]
好吧，原来版本问题。
